# Generated by Django 5.1.3 on 2024-11-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='access_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
